name: Renovate config CI
description: Renovate config CI

inputs:
  target:
    required: false
    description: Target filename

runs:
  using: composite
  steps:
  - uses: actions/checkout@v4.2.2
  - name: Use Node.js
    uses: actions/setup-node@v4.1.0
    with:
      node-version: lts/*
      check-latest: true
  - name: renovate test
    shell: bash
    run: npx --yes --package renovate -- renovate-config-validator --strict ${{ inputs.target }}
