name: Renovate config CI

on:
  workflow_call:
    inputs:
      target:
        type: string
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2
    - name: Use Node.js
      uses: actions/setup-node@v4.2.0
      with:
        node-version: lts/*
        check-latest: true
    - name: renovate test
      run: npx --yes --package renovate -- renovate-config-validator --strict ${{ inputs.target }}
