name: Rust test

on:
  workflow_call:
    inputs:
      clippy:
        required: false
        type: boolean
        default: false

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: Enable cache
      uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
    - name: Install the stable toolchain
      if: ${{ !github.event.inputs.clippy }}
      uses: dtolnay/rust-toolchain@4be7066ada62dd38de10e7b70166bc74ed198c30 # stable
      with:
        toolchain: 1.96.1
    - name: Install the stable toolchain
      if: ${{ github.event.inputs.clippy }}
      uses: dtolnay/rust-toolchain@4be7066ada62dd38de10e7b70166bc74ed198c30 # stable
      with:
        toolchain: 1.96.1
        components: clippy
    - name: Build
      run: cargo build --verbose --workspace
    - name: Clippy
      if: ${{ github.event.inputs.clippy }}
      uses: giraffate/clippy-action@13b9d32482f25d29ead141b79e7e04e7900281e0 # v1.0.1
      with:
        reporter: 'github-pr-review'
    - name: Run tests
      run: cargo test --verbose --workspace
