name: Rust test

on:
  workflow_call:
    inputs:
      clippy:
        required: false
        type: boolean
        default: false

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2
    - name: Enable cache
      uses: Swatinem/rust-cache@82a92a6e8fbeee089604da2575dc567ae9ddeaab # v2.7.5
    - name: Install the stable toolchain
      if: ${{ !github.event.inputs.clippy }}
      uses: dtolnay/rust-toolchain@7b1c307e0dcbda6122208f10795a713336a9b35a # stable
    - name: Install the stable toolchain
      if: ${{ github.event.inputs.clippy }}
      uses: dtolnay/rust-toolchain@7b1c307e0dcbda6122208f10795a713336a9b35a # stable
      with:
        components: clippy
    - name: Build
      run: cargo build --verbose --workspace
    - name: Clippy
      if: ${{ github.event.inputs.clippy }}
      uses: giraffate/clippy-action@13b9d32482f25d29ead141b79e7e04e7900281e0 # v1.0.1
      with:
        reporter: 'github-pr-review'
    - name: Run tests
      run: cargo test --verbose --workspace
