name: Rust test

on:
  workflow_call:
    inputs:
      clippy:
        required: false
        type: boolean
        default: false

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2
    - name: Enable cache
      uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6 # v2.7.8
    - name: Install the stable toolchain
      if: ${{ !github.event.inputs.clippy }}
      uses: dtolnay/rust-toolchain@56f84321dbccf38fb67ce29ab63e4754056677e0 # stable
      with:
        toolchain: stable
    - name: Install the stable toolchain
      if: ${{ github.event.inputs.clippy }}
      uses: dtolnay/rust-toolchain@56f84321dbccf38fb67ce29ab63e4754056677e0 # stable
      with:
        toolchain: stable
        components: clippy
    - name: Build
      run: cargo build --verbose --workspace
    - name: Clippy
      if: ${{ github.event.inputs.clippy }}
      uses: giraffate/clippy-action@13b9d32482f25d29ead141b79e7e04e7900281e0 # v1.0.1
      with:
        reporter: 'github-pr-review'
    - name: Run tests
      run: cargo test --verbose --workspace
