name: Rust test

on:
  workflow_call:
    inputs:
      clippy:
        required: false
        type: boolean
        default: false

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2
    - name: Enable cache
      uses: Swatinem/rust-cache@f13886b937689c021905a6b90929199931d60db1 # v2.8.1
    - name: Install the stable toolchain
      if: ${{ !github.event.inputs.clippy }}
      uses: dtolnay/rust-toolchain@b3b07ba8b418998c39fb20f53e8b695cdcc8de1b # stable
      with:
        toolchain: stable
    - name: Install the stable toolchain
      if: ${{ github.event.inputs.clippy }}
      uses: dtolnay/rust-toolchain@b3b07ba8b418998c39fb20f53e8b695cdcc8de1b # stable
      with:
        toolchain: stable
        components: clippy
    - name: Build
      run: cargo build --verbose --workspace
    - name: Clippy
      if: ${{ github.event.inputs.clippy }}
      uses: giraffate/clippy-action@13b9d32482f25d29ead141b79e7e04e7900281e0 # v1.0.1
      with:
        reporter: 'github-pr-review'
    - name: Run tests
      run: cargo test --verbose --workspace
