name: Rust test

on:
  workflow_call:
    inputs:
      clippy:
        required: false
        type: boolean
        default: false

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2
    - name: Enable cache
      uses: Swatinem/rust-cache@f0deed1e0edfc6a9be95417288c0e1099b1eeec3 # v2.7.7
    - name: Install the stable toolchain
      if: ${{ !github.event.inputs.clippy }}
      uses: dtolnay/rust-toolchain@c5a29ddb4d9d194e7c84ec8c3fba61b1c31fee8c # stable
      with:
        toolchain: stable
    - name: Install the stable toolchain
      if: ${{ github.event.inputs.clippy }}
      uses: dtolnay/rust-toolchain@c5a29ddb4d9d194e7c84ec8c3fba61b1c31fee8c # stable
      with:
        toolchain: stable
        components: clippy
    - name: Build
      run: cargo build --verbose --workspace
    - name: Clippy
      if: ${{ github.event.inputs.clippy }}
      uses: giraffate/clippy-action@13b9d32482f25d29ead141b79e7e04e7900281e0 # v1.0.1
      with:
        reporter: 'github-pr-review'
    - name: Run tests
      run: cargo test --verbose --workspace
